/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LangChar125RouteRouteImport } from './routes/{-$lang}/route'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125FaqIndexRouteImport } from './routes/{-$lang}/faq/index'
import { Route as Char123LangChar125BlogIndexRouteImport } from './routes/{-$lang}/blog/index'
import { Route as Char123LangChar125CategoryCategoryRouteImport } from './routes/{-$lang}/category/$category'
import { Route as Char123LangChar125BlogSlugRouteImport } from './routes/{-$lang}/blog/$slug'

const Char123LangChar125RouteRoute = Char123LangChar125RouteRouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125FaqIndexRoute =
  Char123LangChar125FaqIndexRouteImport.update({
    id: '/faq/',
    path: '/faq/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125BlogIndexRoute =
  Char123LangChar125BlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125CategoryCategoryRoute =
  Char123LangChar125CategoryCategoryRouteImport.update({
    id: '/category/$category',
    path: '/category/$category',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125BlogSlugRoute =
  Char123LangChar125BlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/blog/$slug': typeof Char123LangChar125BlogSlugRoute
  '/{-$lang}/category/$category': typeof Char123LangChar125CategoryCategoryRoute
  '/{-$lang}/blog/': typeof Char123LangChar125BlogIndexRoute
  '/{-$lang}/faq/': typeof Char123LangChar125FaqIndexRoute
}
export interface FileRoutesByTo {
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/blog/$slug': typeof Char123LangChar125BlogSlugRoute
  '/{-$lang}/category/$category': typeof Char123LangChar125CategoryCategoryRoute
  '/{-$lang}/blog': typeof Char123LangChar125BlogIndexRoute
  '/{-$lang}/faq': typeof Char123LangChar125FaqIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/blog/$slug': typeof Char123LangChar125BlogSlugRoute
  '/{-$lang}/category/$category': typeof Char123LangChar125CategoryCategoryRoute
  '/{-$lang}/blog/': typeof Char123LangChar125BlogIndexRoute
  '/{-$lang}/faq/': typeof Char123LangChar125FaqIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lang}'
    | '/{-$lang}/'
    | '/{-$lang}/blog/$slug'
    | '/{-$lang}/category/$category'
    | '/{-$lang}/blog/'
    | '/{-$lang}/faq/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$lang}'
    | '/{-$lang}/blog/$slug'
    | '/{-$lang}/category/$category'
    | '/{-$lang}/blog'
    | '/{-$lang}/faq'
  id:
    | '__root__'
    | '/{-$lang}'
    | '/{-$lang}/'
    | '/{-$lang}/blog/$slug'
    | '/{-$lang}/category/$category'
    | '/{-$lang}/blog/'
    | '/{-$lang}/faq/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LangChar125RouteRoute: typeof Char123LangChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/faq/': {
      id: '/{-$lang}/faq/'
      path: '/faq'
      fullPath: '/{-$lang}/faq/'
      preLoaderRoute: typeof Char123LangChar125FaqIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/blog/': {
      id: '/{-$lang}/blog/'
      path: '/blog'
      fullPath: '/{-$lang}/blog/'
      preLoaderRoute: typeof Char123LangChar125BlogIndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/category/$category': {
      id: '/{-$lang}/category/$category'
      path: '/category/$category'
      fullPath: '/{-$lang}/category/$category'
      preLoaderRoute: typeof Char123LangChar125CategoryCategoryRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/blog/$slug': {
      id: '/{-$lang}/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$lang}/blog/$slug'
      preLoaderRoute: typeof Char123LangChar125BlogSlugRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
  }
}

interface Char123LangChar125RouteRouteChildren {
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125BlogSlugRoute: typeof Char123LangChar125BlogSlugRoute
  Char123LangChar125CategoryCategoryRoute: typeof Char123LangChar125CategoryCategoryRoute
  Char123LangChar125BlogIndexRoute: typeof Char123LangChar125BlogIndexRoute
  Char123LangChar125FaqIndexRoute: typeof Char123LangChar125FaqIndexRoute
}

const Char123LangChar125RouteRouteChildren: Char123LangChar125RouteRouteChildren =
  {
    Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
    Char123LangChar125BlogSlugRoute: Char123LangChar125BlogSlugRoute,
    Char123LangChar125CategoryCategoryRoute:
      Char123LangChar125CategoryCategoryRoute,
    Char123LangChar125BlogIndexRoute: Char123LangChar125BlogIndexRoute,
    Char123LangChar125FaqIndexRoute: Char123LangChar125FaqIndexRoute,
  }

const Char123LangChar125RouteRouteWithChildren =
  Char123LangChar125RouteRoute._addFileChildren(
    Char123LangChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LangChar125RouteRoute: Char123LangChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
